version: '3'
services:
  mkdocs:
    image: jssdocente/mkdocs-daw
    build:
      context: ./.docker
      dockerfile: dockerfile
      
    container_name: Mkdocs-bd2526
    ports:
      - "8006:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true