/**********************************************************************************
  Netflix database for MYSQL
  Description: Creates and populates the Netflix database.
  Created on: 2026-02-04T00:13:39.350863207Z
  Author: Luis Rocha
  License: https://github.com/lerocha/netflixdb/blob/main/LICENSE
   
  WARNING: This file was generated by a tool and changes to this file will be lost
           when this file is regenerated.
***********************************************************************************/

DROP DATABASE IF EXISTS Netflix;
CREATE DATABASE Netflix CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE Netflix;

    create table movie (
        id bigint not null auto_increment comment 'Primary unique identifier',
        created_date datetime(6) not null comment 'Date when this record was created',
        modified_date datetime(6) not null comment 'Date when this record was last modified',
        available_globally bit comment 'A flag that indicates if this title is available outside US',
        locale varchar(10) comment 'The original language/region of the movie',
        original_title varchar(255) character set utf8 comment 'The movie title in its original language',
        release_date date comment 'Date when this title was released',
        runtime bigint comment 'The total runtime in minutes',
        title varchar(255) character set utf8 not null comment 'The movie title',
        primary key (id)
    ) engine=InnoDB;

    create table season (
        id bigint not null auto_increment comment 'Primary unique identifier',
        created_date datetime(6) not null comment 'Date when this record was created',
        modified_date datetime(6) not null comment 'Date when this record was last modified',
        original_title varchar(255) character set utf8 comment 'The season title in its original language',
        release_date date comment 'Date when this title was released',
        runtime bigint comment 'The total runtime in minutes',
        season_number integer comment 'The season number',
        title varchar(255) character set utf8 not null comment 'The season title',
        tv_show_id bigint comment 'The TV show that this season belongs to',
        primary key (id)
    ) engine=InnoDB;

    create table tv_show (
        id bigint not null auto_increment comment 'Primary unique identifier',
        created_date datetime(6) not null comment 'Date when this record was created',
        modified_date datetime(6) not null comment 'Date when this record was last modified',
        available_globally bit comment 'A flag that indicates if this title is available outside US',
        locale varchar(10) comment 'The original language/region of the TV show',
        original_title varchar(255) character set utf8 comment 'The TV show title in its original language',
        release_date date comment 'Date when this title was released',
        title varchar(255) character set utf8 not null comment 'The TV show title',
        primary key (id)
    ) engine=InnoDB;

    create table view_summary (
        id bigint not null auto_increment comment 'Primary unique identifier',
        created_date datetime(6) not null comment 'Date when this record was created',
        modified_date datetime(6) not null comment 'Date when this record was last modified',
        cumulative_weeks_in_top10 integer comment 'The number of cumulative weeks in top 10 list',
        duration enum ('SEMI_ANNUALLY','WEEKLY') not null comment 'The duration of the period this summary refers to',
        end_date date not null comment 'The last day of the period this summary refers to',
        hours_viewed integer not null comment 'The total hours viewed during this period',
        start_date date not null comment 'The first day of the period this summary refers to',
        view_rank integer comment 'The rank during this period',
        views integer comment 'The number of views during this period',
        movie_id bigint comment 'The movie for this weekly summary',
        season_id bigint comment 'The season for this weekly summary',
        primary key (id)
    ) engine=InnoDB;

    create index idx_movie_title_runtime 
       on movie (title, runtime);

    create index idx_season_title_runtime 
       on season (title, runtime);

    create index fk_season_tv_show_id 
       on season (tv_show_id);

    alter table tv_show 
       add constraint idx_tv_show_title unique (title);

    alter table season 
       add constraint fk_season_tv_show_id 
       foreign key (tv_show_id) 
       references tv_show (id);

    alter table view_summary 
       add constraint fk_view_summary_movie_id 
       foreign key (movie_id) 
       references movie (id);

    alter table view_summary 
       add constraint fk_view_summary_season_id 
       foreign key (season_id) 
       references season (id);
